### ISSUE TITLE
Panic when exporting a top-level function that takes a resource as an argument

### ISSUE THREAD

**Issue by rylev** [peterhuene/wac#62]
Take a component with the following wit:

```wit
package component:comp;

world my-world {
    use my-interface.{my-resource};
    export my-func: func(r: my-resource);
}

interface my-interface {
    resource my-resource {}
}
```

And the following wac file:

```
package example:composition;

let comp = new example:comp {...};
export comp.my-func;
```

You will get the following panic:

```
thread 'main' panicked at crates/wac-parser/src/resolution/encoding.rs:191:38:
internal error: entered unreachable code: resource cannot be imported at the top-level
```

Importing resources is indeed not possible, but it seems the transitive dependency on `my-interface` gets lost along the way.

**Comment by rylev** [comment]
This manifests itself as a slightly different error using `wac-graph` rather than the `wac` cli. 

With the following instantiation and the wit description from above, we see an error:

```json
{
    "packages": [
        {
            "name": "example:example",
            "path": "world.wit"
        }
    ],
    "nodes": [
        {
            "type": "instantiation",
            "package": 0
        },
        {
            "type": "alias",
            "source": 0,
            "export": "my-func"
        }
    ],
    "exports": [
        {
            "node": 1,
            "name": "my-func"
        }
    ]
}
```

The panic emitted from this is:

```
thread 'encoding' panicked at crates/wac-graph/src/encoding.rs:202:34:
cannot encode a resource
```

In the input component generated in the test described above, the resource import is encoded like so:

```wat
  (type (;0;)
    (instance
      (export (;0;) "my-resource" (type (sub resource)))
    )
  )
  (import "example:example/my-interface" (instance (;0;) (type 0)))
  (alias export 0 "my-resource" (type (;1;)))
  (import "my-resource" (type (;2;) (eq 1)))
```

Presumably, in the test the "composed" component would encode the resource import just like this.
